AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'PolyHack 2023 - Mindful Beans Backend Stack

  '
Resources:
  NodeJSHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://hacklah-2023-mindful-beans-backend/hacklah-2023-mindful-beans-backend/dev/24854d40fbd447f8fc3eadd55415661e
      Handler: mainHandler.app
      Runtime: nodejs16.x
      Architectures:
      - x86_64
      Events:
        test:
          Type: Api
          Properties:
            Path: /test
            Method: GET
    Metadata:
      SamResourceId: NodeJSHandler
